### ISSUE TITLE
Use plain HTML rather than pug?

### ISSUE THREAD

**Issue by fralonra** [viewweiwu/vue-tabs-chrome#1]
I believe that it it a burden that one should add a loader for pug in his project if he wants to import this component directly.
Could you consider using plain HTML rather than pug in the template?

**Comment by viewweiwu** [comment]
抱歉回的这么晚，不用担心，编译出来的不是 pug，所以并不会添加额外的安装包。

**Comment by yexiaodong** [comment]
如何导入该组件？我的导入无效
