### ISSUE TITLE
引入组件报错

### ISSUE THREAD

**Issue by yexiaodong** [viewweiwu/vue-tabs-chrome#13]
代码：
import VueTabsChrome from 'vue-tabs-chrome'
    components: {
        VueTabsChrome
    },

错误信息：to mount component: template or render function not defined.

**Comment by viewweiwu** [comment]
import VueTabsChrome from 'vue-tabs-chrome'
import Vue from 'vue'
Vue.use(VueTabsChrome)

**Comment by yexiaodong** [comment]
![image](https://user-images.githubusercontent.com/13914749/88776770-fdc5ae80-d1b8-11ea-8e55-5a9b6c5ac694.png)
不行

**Comment by viewweiwu** [comment]
什么版本的 vue-tabs-chrome

**Comment by viewweiwu** [comment]
以及贴完整代码

**Comment by yexiaodong** [comment]
"vue-tabs-chrome": "^0.5.1",

main.js
import VueTabsChrome from 'vue-tabs-chrome'
Vue.use(VueTabsChrome)

home.vue
<template>
<div class="home">
    
    <config-files />
    <config-right/>
    <vue-tabs-chrome v-model="tab" :tabs="tabs" />
</div>
</template>

<script>
import ConfigFiles from '@/components/config/Files.vue'

export default {
    name: 'home',
    components: {
        ConfigLeft,
        ConfigCenter,
        ConfigRight,
        ConfigFiles,
    },
    data() {
        return {
            tab: 'google',
            tabs: [{
                    label: 'google',
                    key: 'google',
                    closable: false,
                    favico: require('@/assets/logo.png')
                },
                {
                    label: 'facebook',
                    key: 'facebook',
                    favico: require('@/assets/logo.png')
                },
                {
                    label: 'New Tab',
                    key: 'costom key',
                    favico: (h, { tab, index }) => {
                        return h('span', tab.label)
                    }
                }
            ]
        }
    },
    methods: {},
    mounted() {},
}
</script>

<style lang="scss">
.home {
    display: flex;

    .lHeader {
        display: none;
    }
}
</style>

**Comment by viewweiwu** [comment]
chrome 版本呢

**Comment by viewweiwu** [comment]
把  favico 删掉试试

**Comment by yexiaodong** [comment]
![image](https://user-images.githubusercontent.com/13914749/88780773-0ff61b80-d1be-11ea-82b2-a3ffd7907a09.png)
![image](https://user-images.githubusercontent.com/13914749/88780793-14223900-d1be-11ea-98ab-773d6ae12e0b.png)
删除favico 一样不行

**Comment by viewweiwu** [comment]
试了一下 codesandbox。
看看能不能跑起来，这个是一个最简单的 demo
https://codesandbox.io/s/suspicious-lalande-w89l4?fontsize=14&hidenavigation=1&theme=dark
![image](https://user-images.githubusercontent.com/14287892/88781401-eee1fa80-d1be-11ea-9de0-5e628a3b58d7.png)

**Comment by yexiaodong** [comment]
这个可以

**Comment by viewweiwu** [comment]
那你看看，这个跟你项目有什么地方不一样，找找看。

**Comment by yexiaodong** [comment]
ok，谢谢

**Comment by yexiaodong** [comment]
找到错误原因了：key: 'costom key', key值不能有空格

**Comment by viewweiwu** [comment]
ok，刚刚没有看出来，那就不要在 key 里面使用空格了
