### ISSUE TITLE
给每个tab添加独立的类（控制x的样式）

### ISSUE THREAD

**Issue by yexiaodong** [viewweiwu/vue-tabs-chrome#15]
希望可以类似VS code修过文件但未保存那样的效果
![image](https://user-images.githubusercontent.com/13914749/90407502-2fa3a400-e0d9-11ea-902f-89c167c83992.png)

**Comment by viewweiwu** [comment]
是有这个样式的，demo 里面有这个例子。
如果是 active 状态，会有 active 样式的。
其它的话跟各自的 key 有关 tab-key。
![image](https://user-images.githubusercontent.com/14287892/90482929-8b683e80-e166-11ea-98f8-3db91ec21f62.png)

**Comment by yexiaodong** [comment]
不是这种效果。我的项目是一个编辑器，我希望当内容有修改但未保存时，tab的关闭按钮改为圆点（类似VS code的那种效果）。key只能在新增时维护，没有update方法（只有addTab、removeTab、getTabs方法）。

**Comment by viewweiwu** [comment]
可以的，
```
[
        {
          label: 'google',
          key: 'google',
          favico: require('../assets/google.jpg'),
          class: 'xxxxxx'
        }
]
```

我可以在每个 tab 单独给个样式，这样子你可以根据 class 改变样子了。

**Comment by yexiaodong** [comment]
this.tabs[0].key='welcome-change-tab' 这样修改key后，无法切换到该tab了

**Comment by viewweiwu** [comment]
不要去改变 key，会出问题的

**Comment by yexiaodong** [comment]
我不是要独立的样式，我是想动态添加class到当前存在的tab上

**Comment by viewweiwu** [comment]
可以的，现在还不支持每个 tab 单独给 class，我给加一个特性，每个 tab 可以独立拥有样式，你可以改这个样式

**Comment by viewweiwu** [comment]
[
        {
          label: 'google',
          class: 'xxxxxx'
        }
]

像这样子，你可以控制这个 class

**Comment by yexiaodong** [comment]
好的，谢谢

**Comment by viewweiwu** [comment]
更新到 0.6.0。
https://github.com/viewweiwu/vue-tabs-chrome/blob/master/examples/example/example-custom-close.vue。
demo 第 4 个例子 https://viewweiwu.github.io/vue-tabs-chrome/

**Comment by viewweiwu** [comment]
![image](https://user-images.githubusercontent.com/14287892/90587665-8362da00-e20c-11ea-82e1-abcb9100b95d.png)

**Comment by yexiaodong** [comment]
已经可以了，谢谢
