### ISSUE TITLE
当tab宽度<=80px时，可以隐藏非当前tab的close图标吗

### ISSUE THREAD

**Issue by meteor199** [viewweiwu/vue-tabs-chrome#18]
就像chrome一样：
![image](https://user-images.githubusercontent.com/21106029/92394605-6ad34900-f154-11ea-8073-c5f358e561fc.png)
![image](https://user-images.githubusercontent.com/21106029/92394741-aa019a00-f154-11ea-815a-d1d21d346a40.png)

否则tab的宽度太小，很容易点到关闭按键。

**Comment by viewweiwu** [comment]
这个可能是之后出来的新特性，正在考虑

**Comment by viewweiwu** [comment]
ok，更新到 0.7.1 试试，现在有这个特性了，并且你可以设置 `autoHiddenCloseIconWidth` 的值自由控制临界值，目前是 120。可以看 demo
