### ISSUE TITLE
Nuxt issues

### ISSUE THREAD

**Issue by vipcat** [viewweiwu/vue-tabs-chrome#20]
Hi ! 
Could you please make nuxt version. I was tried to import it in nuxt but it keep error 
`Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.`
Thanks so much

**Comment by viewweiwu** [comment]
Hi!
key must not have spaces.

key: 'test' // ok
key: 'hello world' // error

**Comment by viewweiwu** [comment]
Please check this

**Comment by Tilesto** [comment]
https://github.com/viewweiwu/vue-tabs-chrome#usage

@viewweiwu  So, please fix it here)
![image](https://user-images.githubusercontent.com/28765507/113717446-ea75c600-96eb-11eb-99a6-7ac5bc74da5f.png)

**Comment by viewweiwu** [comment]
@Tilesto 
Thank you.
I was careless.
