### ISSUE TITLE
New Tab button next to tabs

### ISSUE THREAD

**Issue by pjebs** [viewweiwu/vue-tabs-chrome#21]
It would be great if you can add a "add new tab" button next to the row of tabs to add a new tab.
When the button is called, it should call a callback asking for permission to add the new tab. If the callback returns true, then a new tab is added. If not, a new tab is not added.

**Comment by pjebs** [comment]
@viewweiwu @victoralagwu

**Comment by viewweiwu** [comment]
Like this?
https://codesandbox.io/s/hungry-brahmagupta-e6pwr?file=/src/App.vue

**Comment by pjebs** [comment]
![image](https://user-images.githubusercontent.com/5377970/93728496-7ff3b180-fc03-11ea-9269-177a419806eb.png)

Like this: @viewweiwu

**Comment by pjebs** [comment]
See the `+` button: https://github.com/adamschwartz/chrome-tabs/pull/55

When pressed, it should call a `callback` asking for permission to add a new tab or not.

**Comment by viewweiwu** [comment]
v0.8.0

feat: add after slots
feat: add drag events

see demo3 & last demo
https://viewweiwu.github.io/vue-tabs-chrome/

**Comment by pjebs** [comment]
Thank you so much @viewweiwu
