### ISSUE TITLE
New event for dragging

### ISSUE THREAD

**Issue by pjebs** [viewweiwu/vue-tabs-chrome#22]
It would be great if a new event was fired if dragging changes the order.
That way we can get the new order of tabs.

**Comment by viewweiwu** [comment]
v0.8.0

feat: add after slots
feat: add drag events

see demo3 & last demo
https://viewweiwu.github.io/vue-tabs-chrome/

**Comment by pjebs** [comment]
Thank you so much @viewweiwu
