### ISSUE TITLE
custom data

### ISSUE THREAD

**Issue by pjebs** [viewweiwu/vue-tabs-chrome#23]
In the docs:

Attributes | Description | Type | Default
-- | -- | -- | --
label | tab label | String | -
key | tab key | String | -
class | tab class | String | -
closable | tab closable | Boolean | true
favico | tab favico. Custom favico renderer. It uses Vue's render function. It accepts two arguments: the first is h, the second is an object. including tab and index

**Comment by pjebs** [comment]
Can we add our own custom data as an attribute. Obviously your library will ignore it (which is what we want), but as the tabs get moved around etc, the object associated with each tab will maintain our custom data:

eg.


```js
{
label: "[1] Tab 1",
closable: true,
custom: {
name: "dsagsadg",
time_from: "13:00"
}
}
```

**Comment by pjebs** [comment]
@victoralagwu @viewweiwu

**Comment by viewweiwu** [comment]
see sandbox
https://codesandbox.io/s/hungry-brahmagupta-e6pwr?file=/src/App.vue
