### ISSUE TITLE
Tabs are behind the main tab

### ISSUE THREAD

**Issue by japasanto** [viewweiwu/vue-tabs-chrome#27]
Hi

  Thanks for the package, but i really dont know whats happening, my tabs are behind the main one:

<img width="1332" alt="Captura de ecrã 2020-12-04, às 23 44 57" src="https://user-images.githubusercontent.com/25348458/101225978-d8770e80-368a-11eb-9bae-f1b02934c593.png">

You can see the separators but the tabs are behind the main one...i know that because i had some left: to one of the tabs and it appeared

**Comment by viewweiwu** [comment]
Thank you for using it.
Can you please provide the code.

**Comment by viewweiwu** [comment]
Maybe it's a blank tab with a missing key
