### ISSUE TITLE
Add specific component to route

### ISSUE THREAD

**Issue by shamsail** [viewweiwu/vue-tabs-chrome#28]
Hi, I want to use this package with specified component. Can you let me know how I can add specific data/component/tab material to specific tab. In examples, there is same <div> that is showing up on all tabs

Like, tabs content

**Comment by viewweiwu** [comment]
Hi
specified component?
Does it mean the specified style?
like this?

![image](https://user-images.githubusercontent.com/14287892/102966530-01245280-452b-11eb-8ca3-18a1b95f6c63.png)


https://codesandbox.io/s/gracious-banach-8em8q?file=/src/App.vue

**Comment by shamsail** [comment]
Nope, it means separate content for separate tabs. how to implement this thing? like google tab has it's own content and Facebook tab has it's own and so on.. Thanks for your response

**Comment by viewweiwu** [comment]
Sorry...
No plans to support this feature for now.

**Comment by viewweiwu** [comment]
Sorry
No plans to support this feature for now
