### ISSUE TITLE
Any chance of upgrading to Vue 3?

### ISSUE THREAD

**Issue by m4heshd** [viewweiwu/vue-tabs-chrome#36]
Is there any plan or can I just migrate a fork to Vue 3? I'm afraid if this project is using any breaking functionality,

**Comment by viewweiwu** [comment]
There are plans to support Vue3, almost at the end of the month.

**Comment by m4heshd** [comment]
Aww that's too bad. 🥺 I've got a time critical project that needs this implementation right away. Your project is really impressive and I'm gonna miss out on it.

**Comment by viewweiwu** [comment]
Sorry, I've been busy lately.
I may not have time to support Vue3.
The plan will be scheduled later.

**Comment by m4heshd** [comment]
That's alright. Thank you for your work. I've created one myself from the scratch. It's pretty damn good and planning to share soon. ☺

**Comment by viewweiwu** [comment]
I still took the time to implement it.
But for now there is only a simple api.
Waiting for a few updates, then you can use it!

https://github.com/viewweiwu/vue3-tabs-chrome
