### ISSUE TITLE
Integration with Quasar

### ISSUE THREAD

**Issue by yashchanda721** [viewweiwu/vue-tabs-chrome#37]
How can I integrate this in my quasar app?

**Comment by viewweiwu** [comment]
Need the site to use Vue2, then you can use this dependency.

**Comment by yashchanda721** [comment]
![image](https://user-images.githubusercontent.com/69416880/111612401-6ecadc80-8803-11eb-8474-cc805576747c.png)


It is in Vue2. Can you help with the steps need to taken for integration in my APP.

**Comment by yashchanda721** [comment]
I have follow the steps now I am getting this error.

![image](https://user-images.githubusercontent.com/69416880/111612553-96ba4000-8803-11eb-8429-d77cdd8d5834.png)

**Comment by viewweiwu** [comment]
https://codesandbox.io/s/wandering-sun-5wtpo?file=/src/App.vue
![image](https://user-images.githubusercontent.com/14287892/111613506-8d3bd280-8819-11eb-8e0d-90204d987cd1.png)

**Comment by yashchanda721** [comment]
Thanks! It worked, However new tab button is still not available?

**Comment by viewweiwu** [comment]
https://viewweiwu.github.io/vue-tabs-chrome/

See use cases

https://github.com/viewweiwu/vue-tabs-chrome/blob/master/examples/example/example.vue

**Comment by yashchanda721** [comment]
Thanks very much it is working very smooth!!! Great Job!!!

**Comment by viewweiwu** [comment]
It's my pleasure.
