### ISSUE TITLE
Is there a way to make certain tabs not draggable?

### ISSUE THREAD

**Issue by naomiperry** [viewweiwu/vue-tabs-chrome#39]
I have a use case where I want a few tabs to remain static and others to be draggable. Is this possible?

**Comment by viewweiwu** [comment]
Sorry.
Temporarily not possible.

**Comment by viewweiwu** [comment]
@naomiperry
v0.9.0 can do it.
See last example.

https://viewweiwu.github.io/vue-tabs-chrome/#swap

**Comment by naomiperry** [comment]
@viewweiwu thanks! it looks like when a tab is not draggable, it also isn't clickable though? I made my tabs non draggable and it won't allow me to click them now. it behaves that way in the example also https://viewweiwu.github.io/vue-tabs-chrome/#swap

**Comment by viewweiwu** [comment]
This is a bug, I will fix it.

**Comment by viewweiwu** [comment]
@naomiperry 'v0.9.1' has fixed this bug. 😄

**Comment by naomiperry** [comment]
@viewweiwu does it still trigger the @click event on click?

**Comment by viewweiwu** [comment]
@naomiperry try 'v0.9.2'.

https://codesandbox.io/s/vibrant-kare-0t2wx?file=/src/App.vue

**Comment by naomiperry** [comment]
@viewweiwu  yep that worked! thanks for fixing it so fast!

**Comment by viewweiwu** [comment]
It's my pleasure!

**Comment by ManojAmarasekara** [comment]
I'm adding false to swap and drag when I'm making the tab. But still I can swap/drag them

```
    addTab(tabDetails) {
      const item = `tab${Math.random()}`;
      const newTabs = [
        {
          label: tabDetails.searchTerm,
          key: item,
          favico: tabDetails.bookType === 'book' ? require('../../assets/img/book.png') : require('../../assets/img/ebook.png'),
          swappable: false,
          dragable: false,
        },
      ];
      this.$refs.tab.addTab(...newTabs);
      this.tab = item;
    },
```

what am I missing here? here is my tabs

```
            <vue-tabs-chrome
                ref="tab"
                v-model="tab"
                :tabs="tabs"
                @click="handleClick"
                :on-close="handleClose"
            />
```

**Comment by viewweiwu** [comment]
I did not reproduce the phenomenon you mentioned, please check if the version is higher than v0.9.2.

You can try this demo.

https://codesandbox.io/s/laughing-cannon-nc6xf?file=/src/App.vue

**Comment by viewweiwu** [comment]
@ManojAmarasekara 

I did not reproduce the phenomenon you mentioned, please check if the version is higher than v0.9.2.

You can try this demo.

https://codesandbox.io/s/laughing-cannon-nc6xf?file=/src/App.vue

> I'm adding false to swap and drag when I'm making the tab. But still I can swap/drag them
> 
> ```
>     addTab(tabDetails) {
>       const item = `tab${Math.random()}`;
>       const newTabs = [
>         {
>           label: tabDetails.searchTerm,
>           key: item,
>           favico: tabDetails.bookType === 'book' ? require('../../assets/img/book.png') : require('../../assets/img/ebook.png'),
>           swappable: false,
>           dragable: false,
>         },
>       ];
>       this.$refs.tab.addTab(...newTabs);
>       this.tab = item;
>     },
> ```
> 
> what am I missing here? here is my tabs
> 
> ```
>             <vue-tabs-chrome
>                 ref="tab"
>                 v-model="tab"
>                 :tabs="tabs"
>                 @click="handleClick"
>                 :on-close="handleClose"
>             />
> ```

**Comment by ManojAmarasekara** [comment]
@viewweiwu  does my code has to do something with `@contextmenu="handleClick"`? Cause in my vue code `handleClick is called by click.

**Comment by viewweiwu** [comment]
@ManojAmarasekara 
These are two things that have no influence on each other.
