### ISSUE TITLE
New Tabs always open in the first position

### ISSUE THREAD

**Issue by naomiperry** [viewweiwu/vue-tabs-chrome#40]
`<vue-tabs-chrome ref="settingstab" :minHiddenWidth="120" :maxWidth="160" v-model="tab" :tabs="tabs" @click="handleClick" insert-to-after />
`

my tabs are stored in my state under navigation. My code to add a new tab is based off of code from your example:

`addTab (tab) {
      let item = tab.label.replace(' ', '');
      let newTabs = [
        {
          label: item,
          key: item.toLowerCase(),
          closable: true
        }
      ]
      this.$refs.settingstab.addTab(...newTabs)
      this.tab = item.toLowerCase();`

When I add a new tab, the data is correct, but the tab is always positioned on top of my first tab. When I inspect the element, it doesn't have any css inline style associated to it like the other tabs do, and I get this console error:

`[Vue error] TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.`

I'm also not able to drag the new tab, so it's stuck in place over my other tab

**Comment by naomiperry** [comment]
seems to not work when tabs are coming from computed. I found my own workaround

**Comment by ManojAmarasekara** [comment]
@naomiperry can you share the solution here cause I ran into the same issue

**Comment by naomiperry** [comment]
@ManojAmarasekara  hey sure! 

so my issue was related to me attempting to do this:
`<vue-tabs-chrome ref="settingstab" :minHiddenWidth="120" :maxWidth="160" v-model="tab" :tabs="tabs" @click="handleClick" insert-to-after />`
where the `:tabs=tabs` piece was coming from a computed property. The computed property was the main issue here, so now my working solution is this:

I needed the tabs to be synced with my state so I could manage it across the app and also potentially save user tabs for future logins. so when a tab gets added by a user I do this to add to the existing tabs component like the given examples and also the state for my needs:

`addUserTab(tabToOpen) {
const newTab = {
        label: tabToOpen.label,
        key: ${tabToOpen.label.replace(' ', '-')}, // no spaces allowed in key
        closable: true
      };
      // add our new tab configuration to tabs component and state
      this.$refs.settingstab.addTab(newTab);
      this.$store.commit('ADD_TAB', newTab);`


so since it's in the state, when the user changes routes and all that I want to continue showing my tabs, but needed a workaround from using computed:

`<vue-tabs-chrome theme="custom" ref="settingstab" :minHiddenWidth="120" :maxWidth="160" :value="currentSubTab" :tabs="tabs" @dragstart="handleClick" :onClose="onClose">`

so now I have `tabs` defined as an empty array under data and that's what allows the component to render properly to start:
`data: function() {
    return {
      tabs: []
    };
  }`

and then on mount, I pull the tabs I want to show up from my state and add them:

`  mounted() {
      let mainTabs = this.$store.state.navigation.settingsTabs.concat(this.$store.state.navigation.selectedTabs);
      mainTabs.map(tab => {
        this.addTab(tab);
      });
}`


here is my addTab function to do that:

`addTab(tab) {
      const newTab = {
        label: tab.label,
        key: tab.key,
        closable: tab.closable
      };
      if (!this.$refs.settingstab.getTabs().find(tab => tab.label === newTab.label)) {
        // add our new tab configuration to tabs component if it isn't there already
        this.$refs.settingstab.addTab(newTab);
      }
    }`

**Comment by viewweiwu** [comment]
Because it adds data to the tabs, don't set it in computed.
