### ISSUE TITLE
can we use a mongoose id instead of key in the tabs array.

### ISSUE THREAD

**Issue by b000cw** [viewweiwu/vue-tabs-chrome#42]
This is the current thing I have 
```
{
        label: "Hello",
        desc: "hie",
        key: kkwf23
}

instead I want to work on this
  {
        label: "Hello",
        desc: "hie",
        id: kkwf23
}
```

**Comment by b000cw** [comment]
In the documentation I have seen that by using key props we can achieve this but it is throwing me a error.

**Comment by b000cw** [comment]
I have resolved this issue.
@click i have the 3 attributes in those I am able to get the id.

**Comment by viewweiwu** [comment]
'key' is required.
If you do not use 'key' but 'id', you need to write it like this.

![image](https://user-images.githubusercontent.com/14287892/116400061-2e2b9d80-a85c-11eb-82e7-f202ef64dcba.png)


https://codesandbox.io/s/elegant-cartwright-dgxft?file=/src/App.vue

```html
<template>
  <vue-tabs-chrome v-model="tab" :tabs="tabs" :props="{ key: 'id' }" />
</template>
<script>
  import Vue from 'vue'
  import VueTabsChrome from 'vue-tabs-chrome'

  export default {
    components: {
      VueTabsChrome
    },
    data() {
      return {
        tab: 'google',
        tabs: [
          {
            label: 'google',
            id: 'google'
          },
          {
            label: 'facebook',
            id: 'facebook'
          }
        ]
      }
    }
  }
</script>
```

**Comment by b000cw** [comment]
Thank you for the fast response.

**Comment by viewweiwu** [comment]
It's my pleasure!
