### ISSUE TITLE
'handleClose' isn't working!

### ISSUE THREAD

**Issue by ManojAmarasekara** [viewweiwu/vue-tabs-chrome#49]
I want to do some process when I'm closing the tab. Let's say clear cache or something. I found you mentioned a function called `handleClose` in a different issue. It's in a different language which I didn't understand a single thing. but when I walk through the code I felt this is what I need. So I made my code changed like this.

My tab component in the vue,

`<vue-tabs-chrome ref="tab" v-model="tab" :tabs="tabs" @click="handleClick" :on-close="handleClose" />`

My function in the script,

```
    addTab(tabDetails) {
      const item = `tab${Math.random()}`;
      const newTabs = [
        {
          label: tabDetails.searchTerm,
          key: item,
          favico: tabDetails.bookType === 'book' ? require('../../assets/img/book.png') : require('../../assets/img/ebook.png'),
          dragable: false,
          swappable: false,
        },
      ];
      this.$refs.tab.addTab(...newTabs);
      this.tab = item;
    },
    
    handleClick(e, tab, i) {
      this.tab = tab.key;
      this.handleTabChange(i);
    },

    removeTab() {
      this.$refs.tab.removeTab(this.tab);
    },

    handleClose(tab, key, index) {
      console.log('Handle close called');
      this.$refs.tabs.removeTab(key);

      // remove tab from cache
      cachedHelper.removeTab(cachedHelper.SCREEN_TYPE.keywordSearch, index);

      // when all tabs are closed, direct back to home
      if (this.$props.state.keywordSearch.tabs.length === 0) {
        this.$router.push({ name: 'home' });
      }
    },
```

When I run the program it loads the tab fine. When I press the close button it shows this error message saying 

`vue.esm.js?a026:1897 TypeError: Cannot read property 'removeTab' of undefined`

But I have that function in my script as well. What am I missing here?

<img width="616" alt="Screenshot 2021-06-04 at 2 12 49 PM" src="https://user-images.githubusercontent.com/22044551/120773460-fbea1b80-c53e-11eb-90d4-d28b6435ff2c.png">

**Comment by viewweiwu** [comment]
```javascript
handleClose(tab, key, index) {
  // ...
  return true
}
```

**Comment by ManojAmarasekara** [comment]
Thanks! I removed this line `this.$refs.tabs.removeTab(key);` from the `handleClose` function . And like you mentioned above added `return true;` solved the error and the tab got close as I expected. Thanks again

**Comment by viewweiwu** [comment]
It's my pleasure!
