### ISSUE TITLE
Browser CDN or UNPKG

### ISSUE THREAD

**Issue by amchconsult** [viewweiwu/vue-tabs-chrome#51]
can you give an example of use on CDN as global component.

thank you

**Comment by amchconsult** [comment]
got it working.
sorry.
thanks

**Comment by amchconsult** [comment]
I have one question, can you add horizontal scrolling to it? 
It will be helpful for mobile or when there are too many tabs.
Thank you

**Comment by viewweiwu** [comment]
https://codepen.io/viewweiwu/pen/GRmKaZZ

Sorry, no support for now.
