### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by boomermath** [viewweiwu/vue-tabs-chrome#58]
When importing vue-tabs-chrome into my nuxt app, I get an error message saying window is not defined, and it can be traced back to the minified file in the npm package.

**Comment by boomermath** [comment]
I am using the code from the example in the README by the way

**Comment by viewweiwu** [comment]
Thank you very much for using it.

To use vue-tabs-chrome inside Nuxt, you need to register plugins.

```js
// plugins/vue-tabs-chrome.js

import Vue from "vue";
import VueTabsChrome from "vue-tabs-chrome";

Vue.use(VueTabsChrome);
```

```js
// nuxt.config.js

 plugins: [{ src: "~/plugins/vue-tabs-chrome.js", mode: "client" }],
```

https://go.nuxtjs.dev/config-plugins

**Comment by boomermath** [comment]
This works perfectly, thank you so much for your help!
