### ISSUE TITLE
add routing

### ISSUE THREAD

**Issue by manimovassagh** [viewweiwu/vue-tabs-chrome#65]
Hello, it is not an isssue . I want to know how can i add routing to new tabs? is it possible to add routing to these new tabs?

**Comment by viewweiwu** [comment]
You need to synchronize the relationship between Routing and Tab yourself.

for example:
https://codesandbox.io/s/twilight-forest-mm55be?file=/src/App.vue

**Comment by manimovassagh** [comment]
That is perfect really really Thanks . i tried to put add button inside that but it is not working together. can you please do me a favour and add one add button on the above Sandbox . it will be very helpfull for me . again thanks for the answer 👍

**Comment by viewweiwu** [comment]
@manimovassagh like this?
https://codesandbox.io/s/twilight-forest-mm55be?file=/src/App.vue

**Comment by manimovassagh** [comment]
You are awsome ,
exactly like that .the user click on plus and make a new tab **with the same route that stands in**. for example user is in about page and click addtab and add couple of other about pages. and when click of each tab route to it.
for now when i try to add new tab with the same route that i stands in i become the following error.
I just wanted to thank you very much. lot of thanks from Mainz Germany 👍👍👍👌👌
![Duplictae](https://user-images.githubusercontent.com/74688476/160493463-1e45d4ed-a428-4e85-9e78-ada94a732eb8.JPG)

**Comment by viewweiwu** [comment]
This problem has been fixed.
https://codesandbox.io/s/twilight-forest-mm55be?file=/src/App.vue
<img width="653" alt="image" src="https://user-images.githubusercontent.com/14287892/160735682-a560c514-e1f6-41bf-bb06-f78da4f51829.png">
